### ISSUE TITLE
Receiving 2 or more files from same user at the same time crashes chat

### ISSUE THREAD

**Issue by vituperative** [vituperative/i2pchat#12]

**Comment by wipedlifepotato** [comment]
So i think its trouble of slow connection. not file transfer or two destination of one user.
Its not crashed in linux for me.

**Comment by wipedlifepotato** [comment]
about 2 users -> https://github.com/vituperative/i2pchat/pull/13/files/d954238ee47bd8be8b8747ae3622caa02163f518#diff-95ca46d7499c566a089a37ff6492c68dR278

**Comment by wipedlifepotato** [comment]
so if its not trouble i will delete it.(limit for files). And check it for slow connection maybe. but maybe its too not trouble... maybe even its not actually now.

**Comment by wipedlifepotato** [comment]
Like to fixed

**Comment by vituperative** [comment]
Looks like it's fixed. Closing. Thanks.
