### ISSUE TITLE
Feature Request: binary.tar / appimage

### ISSUE THREAD

**Issue by danrobi11** [vituperative/i2pchat#26]
About a binary or a appimage to make it easy for the non-technical users ?

**Comment by vituperative** [comment]
There's now a compiled 64bit Linux binary available here: https://vituperative.github.io/i2pchat/I2PChat0.2.37-Linux.zip (Qt 5.15 or later required on the host system)

**Comment by danrobi11** [comment]
@vituperative Hey! Thanks for the binary. That will be handy.

> Qt 5.15 or later required on the host system

Ya thats my issue here. I have 5.11 :/
