### ISSUE TITLE
Compilation on Ubuntu Jammy Jellyfish 22.04

### ISSUE THREAD

**Issue by AmyMoriyama** [vituperative/i2pchat#29]
I'll make this short and sweet.

qt5-default is no longer in the repos, so, this has to be done to compile.

Instead of :
_sudo apt-get install -y devscripts build-essential lintian dh-make autoconf qt5-qmake qt5-default libqt5multimedia5 qtmultimedia5-dev libqt5svg5-dev_

It should be:
_sudo apt-get install -y devscripts build-essential lintian dh-make autoconf libqt5multimedia5 qtmultimedia5-dev libqt5svg5-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools_

Instead of:
_qmake-qt5 I2PChat.pro "CONFIG += release"_

It should be:
_qmake I2PChat.pro "CONFIG += release"_

The rest still works.

**Comment by vituperative** [comment]
Thanks for the heads up.  README.md updated accordingly in commit 7412f0e.
