### ISSUE TITLE
When on Ubuntu has error

### ISSUE THREAD

**Issue by Kes332** [vituperative/i2pchat#30]
src/backend/UserManager.cpp: In member function ‘void CUserManager::changeUserPositionInUserList(int, int)’:
src/backend/UserManager.cpp:384:10: error: ‘class QList<CUser*>’ has no member named ‘swapItemsAt’
  384 |   mUsers.swapItemsAt(oldPos, newPos);
      |          ^~~~~~~~~~~
make: *** [Makefile:1304: temp/obj/UserManager.o] Error 1

**Comment by vituperative** [comment]
I2PChat requires Qt 5.14 or newer to build. Please see #25 for a solution. Thanks.
